#!/usr/bin/env python3
"""Generate precomputed wavetables for the synth engine.

Run from the repo root:
    python tools/gen_wavetables.py

Regenerates main/synth/dsp/WaveTables.cpp with the embedded sine table and
bandlimited saw mipmap. Constants must stay in sync with WaveTables.h.
"""
from __future__ import annotations

import math
import os
import sys

SINE_SIZE = 2048
SAW_TABLES = 10
SAW_TABLE_SIZE = 1024
DESIGN_SR = 44100.0
SAW_MAX_FREQ = [
    50.0, 100.0, 200.0, 400.0, 800.0,
    1600.0, 3200.0, 6400.0, 12800.0, 25600.0,
]

PER_LINE = 8


def gen_sine() -> list[float]:
    return [math.sin(2.0 * math.pi * i / SINE_SIZE) for i in range(SINE_SIZE)]


def gen_saw(fmax: float) -> list[float]:
    nyq = DESIGN_SR * 0.5
    n = max(1, int(nyq / fmax))
    out = []
    inv_pi_2 = -2.0 / math.pi
    for i in range(SAW_TABLE_SIZE):
        s = 0.0
        for k in range(1, n + 1):
            s += math.sin(2.0 * math.pi * k * i / SAW_TABLE_SIZE) / k
        out.append(inv_pi_2 * s)
    return out


def fmt_float(x: float) -> str:
    s = f"{x:.9g}"
    # C++ float literals require a decimal point or exponent before the 'f' suffix.
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def write_block(lines: list[str], values: list[float], indent: str) -> None:
    for i in range(0, len(values), PER_LINE):
        chunk = values[i:i + PER_LINE]
        lines.append(indent + ", ".join(fmt_float(v) for v in chunk) + ",")


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.normpath(os.path.join(here, "..", "main", "synth", "dsp", "WaveTables.cpp"))

    sine = gen_sine() + [0.0]
    sine[-1] = sine[0]
    saws = []
    for fmax in SAW_MAX_FREQ:
        saw = gen_saw(fmax)
        saw.append(saw[0])
        saws.append(saw)

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/gen_wavetables.py. Do not edit by hand.")
    lines.append("// Regenerate with: python tools/gen_wavetables.py")
    lines.append("")
    lines.append('#include "synth/dsp/WaveTables.h"')
    lines.append("")
    lines.append("namespace synth::dsp {")
    lines.append("")
    lines.append("const float gSawTableMaxFreq[kSawTables] = {")
    lines.append("    " + ", ".join(fmt_float(v) for v in SAW_MAX_FREQ))
    lines.append("};")
    lines.append("")
    lines.append("float gSineTable[kSineSize + 1] = {")
    write_block(lines, sine, "    ")
    lines.append("};")
    lines.append("")
    lines.append("float gSawTable[kSawTables][kSawTableSize + 1] = {")
    for t, saw in enumerate(saws):
        lines.append(f"    // table {t} (fMax = {SAW_MAX_FREQ[t]:.0f} Hz)")
        lines.append("    {")
        write_block(lines, saw, "        ")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("void initWaveTables() noexcept {")
    lines.append("    // Tables are statically initialised - nothing to do.")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace synth::dsp")
    lines.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path} ({sum(len(s) for s in lines)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
